execute as @a at @s unless block ~ ~1 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~2 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~3 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~4 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~5 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~6 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~7 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~8 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~9 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~10 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~11 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~12 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~13 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~14 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~15 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~16 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~17 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~18 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~19 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~20 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~21 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~22 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~23 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~24 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~25 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~26 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~27 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~28 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~29 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~30 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~31 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~32 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~33 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~34 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~35 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~36 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~37 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~38 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~39 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~40 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~41 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~42 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~43 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~44 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~45 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~46 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~47 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~48 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~49 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~50 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~51 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~52 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~53 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~54 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~55 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~56 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~57 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~58 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~59 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~60 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~61 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~62 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~63 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~64 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~65 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~66 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~67 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~68 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~69 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~70 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~71 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~72 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~73 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~74 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~75 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~76 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~77 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~78 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~79 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~80 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~81 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~82 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~83 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~84 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~85 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~86 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~87 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~88 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~89 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~90 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~91 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~92 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~93 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~94 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~95 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~96 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~97 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~98 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~99 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~100 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~101 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~102 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~103 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~104 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~105 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~106 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~107 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~108 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~109 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~110 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~111 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~112 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~113 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~114 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~115 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~116 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~117 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~118 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~119 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~120 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~121 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~122 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~123 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~124 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~125 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~126 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~127 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~128 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~129 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~130 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~131 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~132 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~133 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~134 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~135 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~136 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~137 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~138 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~139 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~140 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~141 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~142 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~143 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~144 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~145 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~146 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~147 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~148 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~149 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~150 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~151 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~152 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~153 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~154 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~155 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~156 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~157 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~158 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~159 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~160 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~161 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~162 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~163 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~164 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~165 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~166 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~167 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~168 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~169 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~170 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~171 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~172 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~173 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~174 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~175 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~176 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~177 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~178 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~179 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~180 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~181 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~182 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~183 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~184 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~185 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~186 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~187 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~188 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~189 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~190 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~191 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~192 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~193 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~194 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~195 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~196 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~197 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~198 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~199 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~200 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~201 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~202 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~203 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~204 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~205 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~206 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~207 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~208 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~209 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~210 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~211 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~212 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~213 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~214 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~215 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~216 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~217 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~218 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~219 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~220 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~221 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~222 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~223 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~224 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~225 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~226 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~227 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~228 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~229 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~230 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~231 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~232 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~233 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~234 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~235 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~236 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~237 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~238 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~239 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~240 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~241 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~242 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~243 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~244 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~245 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~246 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~247 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~248 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~249 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~250 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~251 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~252 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~253 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~254 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~255 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~256 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~257 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~258 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~259 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~260 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~261 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~262 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~263 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~264 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~265 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~266 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~267 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~268 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~269 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~270 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~271 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~272 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~273 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~274 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~275 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~276 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~277 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~278 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~279 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~280 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~281 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~282 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~283 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~284 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~285 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~286 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~287 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~288 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~289 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~290 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~291 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~292 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~293 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~294 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~295 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~296 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~297 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~298 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~299 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~300 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~301 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~302 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~303 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~304 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~305 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~306 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~307 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~308 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~309 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~310 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~311 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~312 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~313 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~314 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~315 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~316 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~317 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~318 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~319 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~320 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~321 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~322 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~323 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~324 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~325 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~326 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~327 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~328 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~329 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~330 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~331 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~332 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~333 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~334 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~335 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~336 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~337 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~338 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~339 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~340 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~341 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~342 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~343 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~344 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~345 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~346 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~347 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~348 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~349 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~350 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~351 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~352 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~353 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~354 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~355 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~356 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~357 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~358 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~359 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~360 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~361 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~362 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~363 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~364 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~365 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~366 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~367 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~368 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~369 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~370 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~371 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~372 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~373 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~374 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~375 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~376 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~377 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~378 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~379 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~380 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~381 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~382 ~ minecraft:air run tag @s add under_block
execute as @a at @s unless block ~ ~383 ~ minecraft:air run tag @s add under_block